version: '3.1'

services: 
    db:
        image: mariadb:latest
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: trythisPASS
    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        ports:
            - 8080:80
        environment: 
            - PMA_ARBITRARY=1
            - PMA_USER=root
            - PMA_PASSWORD=trythisPASS

